-- V3__rename_to_default_batch.sql
-- 사용자 정의 접두사(tbl_batch_)를 Spring Batch 기본 접두사(BATCH_)로 변경

-- 1. 메인 테이블 이름 변경
RENAME TABLE tbl_batch_JOB_INSTANCE TO BATCH_JOB_INSTANCE;
RENAME TABLE tbl_batch_JOB_EXECUTION TO BATCH_JOB_EXECUTION;
RENAME TABLE tbl_batch_JOB_EXECUTION_PARAMS TO BATCH_JOB_EXECUTION_PARAMS;
RENAME TABLE tbl_batch_STEP_EXECUTION TO BATCH_STEP_EXECUTION;
RENAME TABLE tbl_batch_STEP_EXECUTION_CONTEXT TO BATCH_STEP_EXECUTION_CONTEXT;
RENAME TABLE tbl_batch_JOB_EXECUTION_CONTEXT TO BATCH_JOB_EXECUTION_CONTEXT;

-- 2. 시퀀스 테이블 이름 변경 (Spring Batch 5.x 이상 필수)
RENAME TABLE tbl_batch_STEP_EXECUTION_SEQ TO BATCH_STEP_EXECUTION_SEQ;
RENAME TABLE tbl_batch_JOB_EXECUTION_SEQ TO BATCH_JOB_EXECUTION_SEQ;
RENAME TABLE tbl_batch_JOB_SEQ TO BATCH_JOB_SEQ;